Updated snap for tensorflow GPU.

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -1,25 +1,41 @@
-name: tensorflow-gpu
-version: git
+name: tensorflow
+version: latest
 summary: Machine Learning.
 description: | An open-source software library used for machine learning models.
  
-
-confinement: devmode
+grade: stable
+confinement: classic
 base: core18
 
-architectures:
-  - build-on: i386
+architectures:  
   - build-on: amd64
-  - build-on: armhf
-  - build-on: arm64
-
-parts:
-  tensorflow-gpu:
-    plugin: 
-    source-type: 
-    source: 
-    
+ 
+ tensorflow:
+    plugin: cmake
+    source:
+      # Tensorflow GPU is only available for amd64 (x86_64),
+      # so fail the build on other architectures.
+      - on amd64: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
+      
+    source-type: deb
+    override-build: |
+      ARCHITECTURE=$(dpkg --print-architecture)
+      if [ "${ARCHITECTURE}" = "amd64" ]; then
+        DEB_API="https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb"
+      else
+        echo "ERROR! Tensorflow GPU only produces debs for amd64. Failing the build here."
+        exit 1
+      fi
+      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
+      VERSION=$(echo "${DEB_URL}" | cut -d'_' -f2)
+      echo $VERSION > $SNAPCRAFT_STAGE/version
+      
+      snapcraftctl build
+      
     build-packages:
+      - curl
+      - dpkg
+      - sed
       
     stage-packages:
       - libnvidia-cfg1-390
@@ -60,15 +76,32 @@ parts:
       - xserver-xorg-video-nvidia-390
       - xserver-xorg-video-nvidia-418
 
+    prime:
+      -usr/share/doc
+      -usr/share/fonts
+      -usr/share/icons
+      -usr/share/lintian
+      -usr/share/man
+
+  wrapper:
+    after:
+      - tensorflow
+    plugin: cmake
+    source: files/
+
 apps:
- tensorflow-gpu:
-    command: bin/tensorflow-gpu
-    plugs:
-      - docker
-      - home
-      - network
-      - removable-media
+ tensorflow:
+    command: bin/wrapper $SNAP/usr/share/tensorflow/bin/tensorflow
+    desktop: usr/share/applications/tensorflow.desktop
     environment:
-      "LD_LIBRARY_PATH": "$SNAP/usr/lib/
-	  $SNAPCRAFT_ARCH_TRIPLET"
-      "DISABLE_WAYLAND": "1"
+      # Fallback to XWayland if running in a Wayland session.
+      DISABLE_WAYLAND: 1
+      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
+
+  url-handler:
+    command: bin/wrapper $SNAP/usr/share/tensorflow/bin/tensorflow --open-url
+    desktop: usr/share/applications/tensorflow-url-handler.desktop
+    environment:
+      # Fallback to XWayland if running in a Wayland session.
+      DISABLE_WAYLAND: 1
+      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
